plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

# npmScopes:
#   fluidframework:
#     npmRegistryServer: http://localhost:4873
#     npmAlwaysAuth: false

unsafeHttpWhitelist:
  - "localhost"
